Add meeting minutes for March 2023
ocapn/ocapn pull request #39
Opened 2023-03-27 14:39 UTC by tsyesika

Here are the meeting minutes for the March 2023 meeting. I forgot to take note of who was attending so if you're missing or know of someone who's missing, please let me know and I'll add you.

2023-03-27 18:29 UTC, dckc commented
I just noticed this by way of a notification of a comment on #32.

I'm used to sharing meeting notes causing a notification to participants. But as noted in [Process and goals](https://github.com/ocapn/ocapn/wiki/Process-and-goals)...

> No email list for participants [grumble]

It's important to keep the ball moving, so please tag one person from each of Agoric, Spritely, and capnproto as reviewers. Plus the chair.

2023-03-27 18:46 UTC, ocdtrekkie requested changes

2023-03-27 18:46 UTC, ocdtrekkie commented on meeting-minutes/2023-03-24.md
> +
- Jacob Weisz (ocdtrekkie)

I was silent, but present.

2023-03-27 18:48 UTC, ocdtrekkie commented
> I just noticed this by way of a notification of a comment on #32.

I am "watching" this entire repository on GitHub. I receive an email notification on every new issue creation and comment repo-wide.

2023-03-27 18:50 UTC, dckc reviewed
oops... I somehow have 2 reviews in 2 tabs...

2023-03-27 18:50 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +dckc: this is a writeup from talking with Kris Kowal
```suggestion
dckc: [this demo sketch](https://github.com/ocapn/ocapn/issues/6#issuecomment-1477952429) is a writeup from talking with Kris Kowal and company
```

2023-03-27 18:50 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +Jessica: ETA on those, the Syrup one is ready for review, is ready as a PR on the syrup spec
I believe we did note the URL of the PR during the meeting, so...

```suggestion
Jessica: ETA on those, the Syrup one is ready for review, is ready as [a PR on the syrup spec](https://github.com/ocapn/syrup/pull/9)
```

2023-03-27 18:50 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +
let's skip stage direction such as this in the interest of conciseness

```suggestion
```

2023-03-27 18:55 UTC, dckc reviewed
I don't suppose any of these comments is stop-ship critical, but I do want to see how they're addressed before approving.

2023-03-27 18:55 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +dckc: small amount of hacking I did do was about the coordinated types
```suggestion
dckc: [small amount of hacking](https://github.com/ocapn/ocapn/issues/5#issuecomment-1478965669) I did do was about the core data types
```

2023-03-27 18:55 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +
```suggestion

https://github.com/ocapn/ocapn/issues/5#issuecomment-1478684631 is a pre-meeting comment from markm to largely the same effect

```

2023-03-27 18:55 UTC, dckc commented on meeting-minutes/2023-03-24.md
> +jar286: looks like Tuesday April 25 at 19:00 UTC (next meeting)
```suggestion
# Schedule for next monthly meeting

jar286: looks like Tuesday April 25 at 19:00 UTC (next meeting)
```

Hm... all but the 1st heading should be h2, i.e. `##`.

2023-03-27 19:11 UTC, jar398 commented
@dckc Yes, I'm watching "all activity".  Sometimes I get flooded and miss some things, but overall it hasn't been too burdensome.

2023-04-06 09:45 UTC, tsyesika commented
Sorry this took me a while to get to, I've addressed all the feedback. Thanks!

2023-04-09 03:35 UTC, ocdtrekkie approved these changes

2023-04-09 06:02 UTC, dckc approved these changes

2023-04-26 14:57 UTC, tsyesika commented
I think we can merge this now.

2023-04-26 15:18 UTC, merged